
import java.applet.Applet;
import java.applet.AudioClip;//imports



public class OppsFrame extends javax.swing.JFrame {
    static AudioClip clip1;

    public OppsFrame() {
        initComponents();
        
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        intField = new javax.swing.JTextField();
        deltaIntField = new javax.swing.JTextField();
        doubleField = new javax.swing.JTextField();
        deltaDoubleField = new javax.swing.JTextField();
        intMultBUT = new javax.swing.JButton();
        intDivBUT = new javax.swing.JButton();
        intAddBUT = new javax.swing.JButton();
        intSubBUT = new javax.swing.JButton();
        intModBUT = new javax.swing.JButton();
        intPowBUT = new javax.swing.JButton();
        doubleMultBUT = new javax.swing.JButton();
        doubleDivBUT = new javax.swing.JButton();
        doubleAddBUT = new javax.swing.JButton();
        doubleSubBUT = new javax.swing.JButton();
        doublePowBUT = new javax.swing.JButton();
        donottouchLBL4 = new javax.swing.JTextField();
        donottouchLBL1 = new javax.swing.JTextField();
        donottouchLBL2 = new javax.swing.JTextField();
        donottouchLBL3 = new javax.swing.JTextField();
        clearBUT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Mega Calculator");
        setBackground(new java.awt.Color(255, 153, 0));
        setMinimumSize(new java.awt.Dimension(420, 350));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(intField);
        intField.setBounds(20, 30, 130, 20);

        deltaIntField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deltaIntFieldActionPerformed(evt);
            }
        });
        getContentPane().add(deltaIntField);
        deltaIntField.setBounds(20, 70, 130, 20);
        getContentPane().add(doubleField);
        doubleField.setBounds(250, 30, 130, 20);
        getContentPane().add(deltaDoubleField);
        deltaDoubleField.setBounds(250, 70, 130, 20);

        intMultBUT.setText("*=");
        intMultBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intMultBUTActionPerformed(evt);
            }
        });
        getContentPane().add(intMultBUT);
        intMultBUT.setBounds(40, 100, 150, 23);

        intDivBUT.setText("/=");
        intDivBUT.setToolTipText("");
        intDivBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intDivBUTActionPerformed(evt);
            }
        });
        getContentPane().add(intDivBUT);
        intDivBUT.setBounds(40, 130, 150, 23);

        intAddBUT.setText("+=");
        intAddBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intAddBUTActionPerformed(evt);
            }
        });
        getContentPane().add(intAddBUT);
        intAddBUT.setBounds(40, 160, 150, 23);

        intSubBUT.setText("-=");
        intSubBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intSubBUTActionPerformed(evt);
            }
        });
        getContentPane().add(intSubBUT);
        intSubBUT.setBounds(40, 190, 150, 23);

        intModBUT.setText("%=");
        intModBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intModBUTActionPerformed(evt);
            }
        });
        getContentPane().add(intModBUT);
        intModBUT.setBounds(40, 220, 150, 23);

        intPowBUT.setText("Int^DeltaInt");
        intPowBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intPowBUTActionPerformed(evt);
            }
        });
        getContentPane().add(intPowBUT);
        intPowBUT.setBounds(40, 250, 150, 23);

        doubleMultBUT.setText("*=");
        doubleMultBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleMultBUTActionPerformed(evt);
            }
        });
        getContentPane().add(doubleMultBUT);
        doubleMultBUT.setBounds(199, 100, 150, 23);

        doubleDivBUT.setText("/=");
        doubleDivBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleDivBUTActionPerformed(evt);
            }
        });
        getContentPane().add(doubleDivBUT);
        doubleDivBUT.setBounds(199, 130, 150, 23);

        doubleAddBUT.setText("+=");
        doubleAddBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleAddBUTActionPerformed(evt);
            }
        });
        getContentPane().add(doubleAddBUT);
        doubleAddBUT.setBounds(199, 160, 150, 23);

        doubleSubBUT.setText("-=");
        doubleSubBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleSubBUTActionPerformed(evt);
            }
        });
        getContentPane().add(doubleSubBUT);
        doubleSubBUT.setBounds(199, 190, 150, 23);

        doublePowBUT.setText("Double^DeltaDouble");
        doublePowBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doublePowBUTActionPerformed(evt);
            }
        });
        getContentPane().add(doublePowBUT);
        doublePowBUT.setBounds(200, 250, 150, 23);

        donottouchLBL4.setEditable(false);
        donottouchLBL4.setBackground(new java.awt.Color(0, 0, 0));
        donottouchLBL4.setForeground(new java.awt.Color(255, 255, 255));
        donottouchLBL4.setText("DeltaDouble");
        getContentPane().add(donottouchLBL4);
        donottouchLBL4.setBounds(250, 50, 130, 20);

        donottouchLBL1.setEditable(false);
        donottouchLBL1.setBackground(new java.awt.Color(0, 0, 0));
        donottouchLBL1.setForeground(new java.awt.Color(255, 255, 255));
        donottouchLBL1.setText("Int");
        getContentPane().add(donottouchLBL1);
        donottouchLBL1.setBounds(20, 10, 130, 20);

        donottouchLBL2.setEditable(false);
        donottouchLBL2.setBackground(new java.awt.Color(0, 0, 0));
        donottouchLBL2.setForeground(new java.awt.Color(255, 255, 255));
        donottouchLBL2.setText("DeltaInt");
        getContentPane().add(donottouchLBL2);
        donottouchLBL2.setBounds(20, 50, 130, 20);

        donottouchLBL3.setEditable(false);
        donottouchLBL3.setBackground(new java.awt.Color(0, 0, 0));
        donottouchLBL3.setForeground(new java.awt.Color(255, 255, 255));
        donottouchLBL3.setText("Double");
        getContentPane().add(donottouchLBL3);
        donottouchLBL3.setBounds(250, 10, 130, 20);

        clearBUT.setText("CLEAR");
        clearBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBUTActionPerformed(evt);
            }
        });
        getContentPane().add(clearBUT);
        clearBUT.setBounds(160, 10, 80, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deltaIntFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deltaIntFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deltaIntFieldActionPerformed

    private void intMultBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intMultBUTActionPerformed
   String tempa = intField.getText(); 
String tempb = deltaIntField.getText(); //get number entered
int a = Integer.parseInt(tempa); 

int b = Integer.parseInt(tempb); 

int num = a*b;//mathematicals

intField.setText(Integer.toString(num));//output answer
    }//GEN-LAST:event_intMultBUTActionPerformed

    private void intDivBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intDivBUTActionPerformed
String tempa = intField.getText(); 
String tempb = deltaIntField.getText(); 


int a = Integer.parseInt(tempa); 

int b = Integer.parseInt(tempb); 
if(b==0){
   intField.setText("error(div by 0)"); //div 0 check
}else{

int num = a/b;

intField.setText(Integer.toString(num));}
    }//GEN-LAST:event_intDivBUTActionPerformed

    private void intAddBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intAddBUTActionPerformed
 String tempa = intField.getText(); 
String tempb = deltaIntField.getText(); 

int a = Integer.parseInt(tempa); 

int b = Integer.parseInt(tempb); 

int num = a+b;

intField.setText(Integer.toString(num));
    }//GEN-LAST:event_intAddBUTActionPerformed

    private void intSubBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intSubBUTActionPerformed
 String tempa = intField.getText(); 
String tempb = deltaIntField.getText(); 

int a = Integer.parseInt(tempa); 

int b = Integer.parseInt(tempb); 

int num = a-b;

intField.setText(Integer.toString(num));
    }//GEN-LAST:event_intSubBUTActionPerformed

    private void intModBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intModBUTActionPerformed
String tempa = intField.getText(); 
String tempb = deltaIntField.getText(); 

int a = Integer.parseInt(tempa); 

int b = Integer.parseInt(tempb); 

int num = a%b;

intField.setText(Integer.toString(num));
    }//GEN-LAST:event_intModBUTActionPerformed

    private void intPowBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intPowBUTActionPerformed
String tempa = intField.getText(); 
String tempb = deltaIntField.getText(); 

int a = Integer.parseInt(tempa); 

int b = Integer.parseInt(tempb); 

int num = (int) Math.pow(a, b);

intField.setText(Integer.toString(num));        // TODO add your handling code here:
    }//GEN-LAST:event_intPowBUTActionPerformed

    private void doubleMultBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleMultBUTActionPerformed
String tempa = doubleField.getText(); 
String tempb = deltaDoubleField.getText(); 

double a = Double.parseDouble(tempa); 

double b = Double.parseDouble(tempb); 

double num = a*b;

doubleField.setText(Double.toString(num));
    }//GEN-LAST:event_doubleMultBUTActionPerformed

    private void doubleDivBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleDivBUTActionPerformed
 String tempa = doubleField.getText(); 
String tempb = deltaDoubleField.getText(); 

double a = Double.parseDouble(tempa); 

double b = Double.parseDouble(tempb); 
if(b==0){
   doubleField.setText("error(div by 0)"); 
}else{
double num = a/b;

doubleField.setText(Double.toString(num));}
    }//GEN-LAST:event_doubleDivBUTActionPerformed

    private void doubleAddBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleAddBUTActionPerformed
String tempa = doubleField.getText(); 
String tempb = deltaDoubleField.getText(); 

double a = Double.parseDouble(tempa); 

double b = Double.parseDouble(tempb); 

double num = a+b;

doubleField.setText(Double.toString(num));
    }//GEN-LAST:event_doubleAddBUTActionPerformed

    private void doubleSubBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleSubBUTActionPerformed
String tempa = doubleField.getText(); 
String tempb = deltaDoubleField.getText(); 

double a = Double.parseDouble(tempa); 

double b = Double.parseDouble(tempb); 

double num = a-b;

doubleField.setText(Double.toString(num));
    }//GEN-LAST:event_doubleSubBUTActionPerformed

    private void doublePowBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doublePowBUTActionPerformed
String tempa = doubleField.getText(); 
String tempb = deltaDoubleField.getText(); 

double a = Double.parseDouble(tempa); 

double b = Double.parseDouble(tempb); 

double num =  Math.pow(a, b);

doubleField.setText(Double.toString(num));
    }//GEN-LAST:event_doublePowBUTActionPerformed

    private void clearBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBUTActionPerformed
intField.setText(" ");
deltaIntField.setText(" ");//set all editables to blank
doubleField.setText(" ");
deltaDoubleField.setText(" ");
    }//GEN-LAST:event_clearBUTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OppsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OppsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OppsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OppsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new OppsFrame().setVisible(true);
                clip1 = Applet.newAudioClip(ClassLoader.getSystemResource("sounds/Hatsune_Miku_-_Rolling_Girl_PV_-_VOCALOID.wav"));
        clip1.loop();//hatsune miku rolling girl plays
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBUT;
    private javax.swing.JTextField deltaDoubleField;
    private javax.swing.JTextField deltaIntField;
    private javax.swing.JTextField donottouchLBL1;
    private javax.swing.JTextField donottouchLBL2;
    private javax.swing.JTextField donottouchLBL3;
    private javax.swing.JTextField donottouchLBL4;
    private javax.swing.JButton doubleAddBUT;
    private javax.swing.JButton doubleDivBUT;
    private javax.swing.JTextField doubleField;
    private javax.swing.JButton doubleMultBUT;
    private javax.swing.JButton doublePowBUT;
    private javax.swing.JButton doubleSubBUT;
    private javax.swing.JButton intAddBUT;
    private javax.swing.JButton intDivBUT;
    private javax.swing.JTextField intField;
    private javax.swing.JButton intModBUT;
    private javax.swing.JButton intMultBUT;
    private javax.swing.JButton intPowBUT;
    private javax.swing.JButton intSubBUT;
    // End of variables declaration//GEN-END:variables
public void playSound(){
       clip1 = Applet.newAudioClip(ClassLoader.getSystemResource("fonky.wav"));
        clip1.loop();
   }
   
}
