
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.applet.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sodeerik
 */
public class HangmanGui extends javax.swing.JFrame implements ActionListener{
    JButton[] butArray = new JButton[26];
    int imageNum=0;
    static AudioClip scream;
     ImageIcon [] images = {new ImageIcon(ClassLoader.getSystemResource("images/man1.jpg")),
            new ImageIcon(ClassLoader.getSystemResource("images/man2.jpg")),
            new ImageIcon(ClassLoader.getSystemResource("images/man3.jpg")),
            new ImageIcon(ClassLoader.getSystemResource("images/man4.jpg")),
            new ImageIcon(ClassLoader.getSystemResource("images/man5.jpg")),
            new ImageIcon(ClassLoader.getSystemResource("images/yuno.jpg"))};
    

    /**
     * Creates new form HangmanGui
     */
    public HangmanGui() {
        //Load the background Image 
        
        back = new JLabel(images[imageNum]);
        back.setBounds(0, 160, 700, 250);
        getLayeredPane().add(back, 0);
        JPanel myPanel = new JPanel(); 
        myPanel.setOpaque(false); 
        setContentPane(myPanel); 
        
 //ImageIcon backIm = images[imageNum]; 
 //JLabel backLBL = new JLabel(backIm); //make a JLabel from background image
 
 //Set the bounds of the label to be the whole window 
 //backLBL.setBounds(0, 0, backIm.getIconWidth(), 
 //backIm.getIconHeight()); 
 //getLayeredPane().add(backLBL, new 
 //Integer(Integer.MIN_VALUE)); 
 //JPanel myPanel = new JPanel(); 
 //myPanel.setOpaque(false); 
 //setContentPane(myPanel); 

        initComponents();
        scream =Applet.newAudioClip(ClassLoader.getSystemResource("sounds/scream.wav"));
        dispLabel1.setText(HangmanApp.originalDisp);
        Character c = new Character('A');  //start with 'A'
        for (int i = 0; i < 26; i++) {
            butArray[i] = new JButton(c.toString());
            
            butArray[i].setSize(50, 40);
            butPAN.add(butArray[i]);
            butArray[i].addActionListener(this);
            c++;
        }
    }
    public void actionPerformed(ActionEvent e) {
        //One of the buttons was selected
        for (int i = 0; i < 26; i++) {
            if (e.getSource() == butArray[i]) {
                //get Text from front of
                String letter = ((JButton) e.getSource()).getText();
                System.out.println("Here is the button pressed " + letter);
                ((JButton) e.getSource()).setEnabled(false);
                HangmanApp.a.replaceLetters(letter);
                dispLabel1.setText(HangmanApp.a.getDisplayWord());
                
            }
            
        }
        if(HangmanApp.a.lostGame()){
                for (int i = 0; i < 26; i++) {
            
                butArray[i].setEnabled(false);
               
                guessLabel.setText("You Lose");
            
            
        }
            }
        if(imageNum<HangmanApp.a.getNumWrong()&&HangmanApp.a.getNumWrong()<5){
                    imageNum++;
                    System.out.println("imagenum"+imageNum);
                    getLayeredPane().remove(0);
                     back = new JLabel(images[imageNum]);
        back.setBounds(0, 160, 700, 250);
        getLayeredPane().add(back, 0);
         
                }
        if(HangmanApp.a.getNumWrong()>=5){
            getLayeredPane().remove(0);
                     back = new JLabel(images[5]);
        back.setBounds(0, 0, 800, 550);
        getLayeredPane().add(back, 0);
        JPanel myPanel = new JPanel(); 
        myPanel.setOpaque(false); 
        setContentPane(myPanel); 
        //play scream audio
        playSound();
        }
    }
    public void playSound(){
        scream.play();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butPAN = new javax.swing.JPanel();
        guessLabel = new javax.swing.JTextField();
        dispLabel1 = new javax.swing.JTextField();
        guessBUT = new javax.swing.JButton();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        butPAN.setLayout(new java.awt.GridLayout(2, 13));
        getContentPane().add(butPAN);
        butPAN.setBounds(0, 410, 700, 90);

        guessLabel.setFont(new java.awt.Font("Papyrus", 0, 11)); // NOI18N
        guessLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        guessLabel.setText("type here to guess whole word");
        getContentPane().add(guessLabel);
        guessLabel.setBounds(20, 80, 690, 30);

        dispLabel1.setEditable(false);
        dispLabel1.setFont(new java.awt.Font("Papyrus", 0, 11)); // NOI18N
        dispLabel1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dispLabel1.setText("jTextField1");
        getContentPane().add(dispLabel1);
        dispLabel1.setBounds(20, 40, 690, 30);

        guessBUT.setFont(new java.awt.Font("Papyrus", 0, 11)); // NOI18N
        guessBUT.setText("guess!");
        guessBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessBUTActionPerformed(evt);
            }
        });
        getContentPane().add(guessBUT);
        guessBUT.setBounds(313, 120, 110, 27);
        getContentPane().add(back);
        back.setBounds(0, 160, 700, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guessBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessBUTActionPerformed
        if(guessLabel.getText().compareToIgnoreCase(HangmanApp.a.getWordToGuess())==0){
            dispLabel1.setText(guessLabel.getText()+"~~~~YOU WIN");
            for (int i = 0; i < 26; i++) {
            
                butArray[i].setEnabled(false);
               
                
            
            
        }
        }else{
            for (int i = 0; i < 26; i++) {
            
                butArray[i].setEnabled(false);
               
                guessLabel.setText("You Lose");
            
            
        }
        }
    }//GEN-LAST:event_guessBUTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HangmanGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HangmanGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HangmanGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HangmanGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HangmanGui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JPanel butPAN;
    private javax.swing.JTextField dispLabel1;
    private javax.swing.JButton guessBUT;
    private javax.swing.JTextField guessLabel;
    // End of variables declaration//GEN-END:variables
}
